# Generated by Django 3.2 on 2021-05-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phonenumber',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
