# Generated by Django 3.2 on 2021-05-14 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_user_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phonenumber',
        ),
    ]
