# Generated by Django 3.2.5 on 2021-08-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20210817_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='diving_level',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Scuba Diver', 'Scuba Diver'), ('Advance Scuba Diver', 'Advance Scuba Diver'), ('Technincal Diver', 'Technincal Diver'), ('Rescue Diver', 'Rescue Diver'), ('Instructor', 'Instructor')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
