# Generated by Django 3.2.5 on 2021-08-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_auto_20210817_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='specialty',
            new_name='speciality',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
