# Generated by Django 3.2.5 on 2021-08-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='diving_level',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Scuba Diver', 'Scuba Diver'), ('Advance Scuba Diver', 'Advance Scuba Diver'), ('Technincal Diver', 'Technincal Diver'), ('Rescue Diver', 'Rescue Diver'), ('Instructor', 'Instructor'), ('Others', 'Others')], max_length=20, null=True),
        ),
    ]
