# Generated by Django 3.2.5 on 2021-08-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_registration', '0002_auto_20210818_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodation',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
