# Generated by Django 3.2.5 on 2021-08-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_registration', '0003_alter_accomodation_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divetype',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
