# Generated by Django 3.2.5 on 2021-08-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_registration', '0004_alter_divetype_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Price in $')),
            ],
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Price in $'),
        ),
        migrations.AlterField(
            model_name='divetype',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Price in $'),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price in $'),
        ),
    ]
