# Generated by Django 3.2.5 on 2021-08-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_registration', '0005_auto_20210819_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='divetype',
            name='level',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
