# Generated by Django 3.2.5 on 2021-08-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_registration', '0007_alter_equipement_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
