# Generated by Django 3.2.5 on 2021-08-23 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package_registration', '0009_reservation_reservationdives_reservationequipments_reservationhotel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationdives',
            old_name='dives_id',
            new_name='dives_name',
        ),
        migrations.RenameField(
            model_name='reservationequipments',
            old_name='equipment_id',
            new_name='equipment_name',
        ),
    ]
