# Generated by Django 3.2.5 on 2021-08-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_registration', '0011_auto_20210823_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationhotel',
            old_name='hotel_id',
            new_name='hotel',
        ),
        migrations.RenameField(
            model_name='reservationhotel',
            old_name='room_id',
            new_name='room',
        ),
        migrations.AlterField(
            model_name='reservationhotel',
            name='hotel_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
