# Generated by Django 3.2.5 on 2021-08-23 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package_registration', '0012_auto_20210823_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='package',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='package_registration.package'),
        ),
    ]
