# Generated by Django 3.2.5 on 2021-08-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_registration', '0014_alter_reservation_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationdives',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Price in $'),
        ),
    ]
