# Generated by Django 3.2.5 on 2021-08-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_registration', '0015_reservationdives_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationequipments',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Price in $'),
        ),
        migrations.AddField(
            model_name='reservationhotel',
            name='price_hotel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Price in $'),
        ),
        migrations.AddField(
            model_name='reservationhotel',
            name='price_room',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Price in $'),
        ),
    ]
