# Generated by Django 3.2.5 on 2021-08-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_registration', '0017_package_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='arriva_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
