# Generated by Django 3.2.5 on 2021-08-24 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package_registration', '0018_reservation_arriva_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='arriva_date',
            new_name='arrival_date',
        ),
    ]
