# Generated by Django 3.2.5 on 2021-08-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_registration', '0019_rename_arriva_date_reservation_arrival_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
