# Generated by Django 3.2.5 on 2021-08-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_registration', '0020_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
