# Generated by Django 3.2.5 on 2021-08-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_registration', '0022_alter_reservation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divetype',
            name='level',
            field=models.CharField(blank=True, choices=[('NAUI : Divers', 'NAUI : Divers'), ('NAUI : Specialty', 'NAUI : Specialty'), ('NAUI : Leadership', 'NAUI : Leadership'), ('NAUI : Technical', 'NAUI : Technical')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='type',
            field=models.CharField(blank=True, choices=[('Emergency Equipment', 'Emergency Equipment'), ('Dive Tools', 'Dive Tools'), ('Exposure Protection', 'Exposure Protection'), ('Essentials', 'Essentials'), ('Personal Gear', 'Personal Gear')], max_length=120, null=True),
        ),
    ]
